### ISSUE TITLE
documentation syntax corrections

### ISSUE THREAD

**Issue by ewconnell** [GeorgeLyon/MLIRSwift#1]
Hi George, Happy New Year :) 
I found a few syntax errors in the setup instructions.

The third line `$ cd llvm-project build` should be `$ cd llvm-project/build`

And `ninja $(<path-to-this-repo>/Utilities/mlir-install-target \` is missing an `s`
so it should be `ninja $(<path-to-this-repo>/Utilities/mlir-install-targets \`

cheers, Ed

**Comment by GeorgeLyon** [comment]
Thanks, Ed! I've updated the docs. Feel free (but don't feel required) to submit a PR for anything you believe might be worth changing. I'm sure a bunch of things here are suboptimal.
